"""fix deleted_at nullable

Revision ID: 6f2c2b6e2a4b
Revises: c0cc0ade2957
Create Date: 2026-04-29 21:08:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f2c2b6e2a4b"
down_revision: Union[str, Sequence[str], None] = "c0cc0ade2957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "links",
        "deleted_at",
        existing_type=sa.DateTime(),
        server_default=None,
        nullable=True,
    )
    op.execute("UPDATE links SET deleted_at = NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE links SET deleted_at = now() WHERE deleted_at IS NULL")
    op.alter_column(
        "links",
        "deleted_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        nullable=False,
    )
    # ### end Alembic commands ###
