"""add deleted_at column

Revision ID: c0cc0ade2957
Revises: f7f99b36c006
Create Date: 2026-04-29 19:03:39.192161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cc0ade2957'
down_revision: Union[str, Sequence[str], None] = 'f7f99b36c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'deleted_at')
    # ### end Alembic commands ###
